PROGRAMA NOTACION-CIENTIFICA.
INICIO
    MUEVE 6.022e23 A AVOGADRO.
    MUESTRA "CONSTANTE AVOGADRO: ", AVOGADRO.
    MUEVE 1.5e-10 A PEQUENO.
    MUESTRA "VALOR PEQUENO: ", PEQUENO.
    MUESTRA "OPERACION: ", 2.0 * 1.5e2.
FIN.