PROGRAMA TEST-SI.
INICIO
    MUEVE 10 A VAR-A.
    MUEVE 20 A VAR-B.
    SI VAR-A ES MAYOR QUE VAR-B ENTONCES
        MUESTRA "A ES MAYOR".
    SINO
        MUESTRA "B ES MAYOR O IGUAL".
    FIN-SI.
FIN.