PROGRAMA CALCULADORA-IVA.
INICIO
    MUESTRA "INTRODUCE EL PRECIO DEL PRODUCTO: ".
    LEE PRECIO.
    
    CALCULA IVA = PRECIO * 21 / 100 FIN-CALCULA.
    SUMA IVA A PRECIO.
    
    MUESTRA "EL IVA APLICADO ES: ", IVA.
    MUESTRA "EL TOTAL A PAGAR ES: ", PRECIO.
FIN.