PROGRAMA PRUEBA-ASIG.
INICIO
    MUEVE 10 + 5 * (2 - 1) A RESULTADO.
    CALCULA OTRO-VALOR = RESULTADO * 2 FIN-CALCULA.
    MUESTRA "EL RESULTADO ES: ", RESULTADO.
    MUESTRA "EL DOBLE ES: ", OTRO-VALOR.
FIN.